# BME-237 Applied RNA Bioinformatics problem set 1
aedavids@ucsc.edu
april 2021

In [1]:
import pandas as pd

## Question 11
Find a splice junction that was detected by STAR, but not detected by HISAT2.

What is the chromosome, start position, and end position of the intron that corresponds to this splice junction?

In [2]:
!ls featureCounts.out

Icon?
hisat2.ENCFF000IJ.junctions
hisat2.ENCFF000IJ.junctions.geneIds
hisat2.ENCFF000IJ.junctions.jcounts
hisat2.ENCFF000IJ.junctions.jcounts.primaryGene
hisat2.ENCFF000IJ.junctions.summary
jcount.primaryGenes
junctions.tsv
q18.GL000194.1.3reads.txt
star.ENCFF000IJ.junctions
star.ENCFF000IJ.junctions.geneIds
star.ENCFF000IJ.junctions.jcounts
star.ENCFF000IJ.junctions.jcounts.primaryGenes
star.ENCFF000IJ.junctions.summary

In [3]:
starJunctions   = "featureCounts.out/star.ENCFF000IJ.junctions"
hisat2Junctions = "featureCounts.out/hisat2.ENCFF000IJ.junctions"

In [4]:
starJuncDF   = pd.read_csv( starJunctions, sep='\t', skiprows = 1 )
starJuncDF.rename(columns={ starJuncDF.columns[-1]: "count" }, inplace = True)

hisat2JuncDF = pd.read_csv( hisat2Junctions, sep='\t', skiprows = 1 )
hisat2JuncDF.rename(columns={ hisat2JuncDF.columns[-1]: "count" }, inplace = True)

In [7]:
sc = ["s-" + c for c in starJuncDF]
hc = ["h-" + c for c in hisat2JuncDF]
df = pd.concat( [starJuncDF, hisat2JuncDF], axis=1)
df.columns = sc + hc
df.head()

,s-Geneid,s-Chr,s-Start,s-End,s-Strand,s-Length,s-count,h-Geneid,h-Chr,h-Start,h-End,h-Strand,h-Length,h-count
0,ENSG00000223972.5,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1,11869;12010;12179;12613;12613;12975;13221;1322...,12227;12057;12227;12721;12697;13052;14409;1337...,+;+;+;+;+;+;+;+;+,1735,0,ENSG00000223972.5,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1,11869;12010;12179;12613;12613;12975;13221;1322...,12227;12057;12227;12721;12697;13052;14409;1337...,+;+;+;+;+;+;+;+;+,1735,0
1,ENSG00000227232.5,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,14404;15005;15796;16607;16858;17233;17606;1791...,14501;15038;15947;16765;17055;17368;17742;1806...,-;-;-;-;-;-;-;-;-;-;-,1351,40,ENSG00000227232.5,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,14404;15005;15796;16607;16858;17233;17606;1791...,14501;15038;15947;16765;17055;17368;17742;1806...,-;-;-;-;-;-;-;-;-;-;-,1351,59
2,ENSG00000278267.1,chr1,17369,17436,-,68,0,ENSG00000278267.1,chr1,17369,17436,-,68,0
3,ENSG00000243485.5,chr1;chr1;chr1;chr1;chr1,29554;30267;30564;30976;30976,30039;30667;30667;31109;31097,+;+;+;+;+,1021,0,ENSG00000243485.5,chr1;chr1;chr1;chr1;chr1,29554;30267;30564;30976;30976,30039;30667;30667;31109;31097,+;+;+;+;+,1021,0
4,ENSG00000284332.1,chr1,30366,30503,+,138,0,ENSG00000284332.1,chr1,30366,30503,+,138,0

In [34]:
selectRowsWithReads = ( (df["s-count"] != 0) | (df["h-count"] != 0) )
hasReadsDF = df.loc[ selectRowsWithReads, : ]
hasReadsDF.head()

,s-Geneid,s-Chr,s-Start,s-End,s-Strand,s-Length,s-count,h-Geneid,h-Chr,h-Start,h-End,h-Strand,h-Length,h-count
1,ENSG00000227232.5,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,14404;15005;15796;16607;16858;17233;17606;1791...,14501;15038;15947;16765;17055;17368;17742;1806...,-;-;-;-;-;-;-;-;-;-;-,1351,40,ENSG00000227232.5,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,14404;15005;15796;16607;16858;17233;17606;1791...,14501;15038;15947;16765;17055;17368;17742;1806...,-;-;-;-;-;-;-;-;-;-;-,1351,59
9,ENSG00000238009.6,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,89295;92091;92230;110953;112700;112700;112700;...,91629;92240;92240;111357;112804;112804;112804;...,-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-,3726,0,ENSG00000238009.6,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,89295;92091;92230;110953;112700;112700;112700;...,91629;92240;92240;111357;112804;112804;112804;...,-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-,3726,1
18,ENSG00000279928.2,chr1;chr1;chr1;chr1;chr1,182696;183132;183494;183740;183981,182746;183216;183571;183901;184174,+;+;+;+;+,570,119,ENSG00000279928.2,chr1;chr1;chr1;chr1;chr1,182696;183132;183494;183740;183981,182746;183216;183571;183901;184174,+;+;+;+;+,570,96
19,ENSG00000279457.4,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1,185217;185491;186317;187129;187376;187755;1881...,185350;185559;186469;187287;187577;187890;1882...,-;-;-;-;-;-;-;-;-;-,1397,44,ENSG00000279457.4,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1,185217;185491;186317;187129;187376;187755;1881...,185350;185559;186469;187287;187577;187890;1882...,-;-;-;-;-;-;-;-;-;-,1397,106
21,ENSG00000228463.10,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,257864;257913;258144;258524;258568;261550;2630...,259025;259025;259025;259025;259024;261634;2682...,-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-,8224,0,ENSG00000228463.10,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,257864;257913;258144;258524;258568;261550;2630...,259025;259025;259025;259025;259024;261634;2682...,-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-,8224,2

In [39]:
selectStarOnlyRows = ( (hasReadsDF["s-count"] != 0) & (hasReadsDF["h-count"] == 0) )
starOnlyDF = hasReadsDF.loc[ selectStarOnlyRows ]
starOnlyDF.loc[:,["s-Geneid", "s-count", "s-Length", "h-Geneid", "h-count",]].head()

              s-Geneid  s-count  s-Length           h-Geneid  h-count
119  ENSG00000284740.1        1       660  ENSG00000284740.1        0
275  ENSG00000269925.1        5       393  ENSG00000269925.1        0
320  ENSG00000234546.4       16      2141  ENSG00000234546.4        0
343  ENSG00000202415.1        2       319  ENSG00000202415.1        0
411  ENSG00000201801.1        4       120  ENSG00000201801.1        0

In [48]:
starOnlyDF.loc[ starOnlyDF["s-Geneid"] == "ENSG00000284740.1", ["s-Geneid", "s-Chr", "s-Start", "s-End", "s-Length"] ]

,s-Geneid,s-Chr,s-Start,s-End,s-Length
119,ENSG00000284740.1,chr1;chr1;chr1;chr1,1503250;1503582;1509205;1509205,1503661;1503661;1509452;1509351,660

## Q 16
Find a splice junction that was detected by HISAT2, but not detected by STAR.

What is the chromosome, start position, and end position of the intron that corresponds to this splice junction?

In [50]:
selectHisat2OnlyRows = ( (hasReadsDF["h-count"] != 0) & (hasReadsDF["s-count"] == 0) )
hisat2OnlyDF = hasReadsDF.loc[ selectHisat2OnlyRows ]
hisat2OnlyDF.loc[:,["s-Geneid", "s-count",  "h-Geneid", "h-Length", "h-count",]].head()

              s-Geneid  s-count            h-Geneid  h-Length  h-count
9    ENSG00000238009.6        0   ENSG00000238009.6      3726        1
21  ENSG00000228463.10        0  ENSG00000228463.10      8224        2
34   ENSG00000225630.1        0   ENSG00000225630.1      1044        8
37   ENSG00000229344.1        0   ENSG00000229344.1       682        8
40   ENSG00000198744.5        0   ENSG00000198744.5       547        1

In [51]:
hisat2OnlyDF.loc[ hisat2OnlyDF["h-Geneid"] == "ENSG00000238009.6", ["h-Geneid", "h-Chr", "h-Start", "h-End", "h-Length"] ]

,h-Geneid,h-Chr,h-Start,h-End,h-Length
9,ENSG00000238009.6,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,89295;92091;92230;110953;112700;112700;112700;...,91629;92240;92240;111357;112804;112804;112804;...,3726